### ISSUE TITLE
Does not work with Android

### ISSUE THREAD

**Issue by malachid** [amplafi/htmlcleaner#1]
I had been using the original htmlcleaner on an android app and ran into a threading problem. I decided to give your fork a try but it failed with incompatible APIs.  I am not sure what all was incompatible, but:

E/AndroidRuntime( 1001): java.lang.NoSuchMethodError: java.lang.String.isEmpty
E/AndroidRuntime( 1001): at org.htmlcleaner.TagNode.addAttribute(TagNode.java:215)
E/AndroidRuntime( 1001): at org.htmlcleaner.HtmlTokenizer.tagAttributes(HtmlTokenizer.java:623)
E/AndroidRuntime( 1001): at org.htmlcleaner.HtmlTokenizer.tagStart(HtmlTokenizer.java:451)
E/AndroidRuntime( 1001): at org.htmlcleaner.HtmlTokenizer.start(HtmlTokenizer.java:395)
E/AndroidRuntime( 1001): at org.htmlcleaner.HtmlCleaner.clean(HtmlCleaner.java:415)
E/AndroidRuntime( 1001): at org.htmlcleaner.HtmlCleaner.clean(HtmlCleaner.java:353)

**Comment by andyhot** [comment]
So, took a look - seems if we want to target android we have to be java1.5 compatible (need kostya confirmation on this)
Googling gives value.trim().equals("") as an alternative to value.isEmpty()

**Comment by malachid** [comment]
If I understand correctly, Android 2.1 is a subset of jdk1.5 and 2.2 is a subset of jdk1.6
There are a lot of missing apis (annoying).

**Comment by patmoore** [comment]
o.k. but the question is how hard it is to make the changes to bring it back to 1.5.

malachid - if you could take a look ? you should be able to just compile and find out. I don't think it is that many.

**Comment by patmoore** [comment]
I made a change to handle this particular call - but there maybe more.

**Comment by malachid** [comment]
Hey patmoore,

I am not sure if I am a good test model. I am running Android 2.2 which is closer to 1.6. We should find someone running 2.1 still.

**Comment by patmoore** [comment]
well you are the only one who cares. Also since 2.2 is the latest, who cares about 2.1

**Comment by malachid** [comment]
lol well according to Google (http://developer.android.com/resources/dashboard/platform-versions.html) 42% are still running 2.1, so I am targeting that for development.  I'll see what I can do to get someone to test on 2.1.  Thanks!

**Comment by patmoore** [comment]
o.k. - so the change was made let me know

**Comment by malachid** [comment]
Ok, thanks - I just setup a branch to test it

**Comment by patmoore** [comment]
closed and assumed fixed
