### ISSUE TITLE
Bug in HtmlCleaner.makeTree/closeSnippet

### ISSUE THREAD

**Issue by ghost** [amplafi/htmlcleaner#2]
makeTree called recursively in closeSnippet.
_childBreaks and _openTags fields contains indexes in nodeList which is parameter of makeTree. 
But _childBreaks field value not stored like _openTags. It causes wrong behaviour, NPEs in my case when nodeList.get(index) == null.

**Comment by ghost** [comment]
Don't know how to attach test html file here...

Simple patch:

<pre>
--- a/src/org/htmlcleaner/HtmlCleaner.java
+++ b/src/org/htmlcleaner/HtmlCleaner.java
@@ -875,10 +875,13 @@ public class HtmlCleaner {
                 if (itemsToMove != null) {
                        OpenTags prevOpenTags = _openTags;
                        _openTags = new OpenTags();
+                        ChildBreaks prevChildBreaks = _childBreaks;^M
+                        _childBreaks = new ChildBreaks();^M
                        makeTree(itemsToMove, itemsToMove.listIterator(0));
                     closeAll(itemsToMove);
                     startTagToken.setItemsToMove(null);
                     _openTags = prevOpenTags;
+                        _childBreaks = prevChildBreaks;^M
                 }

                 TagNode newTagNode = createTagNode(startTagToken);
</pre>

**Comment by adrien75018** [comment]
I got the same problem but the patch from all-x doesn't works, is this going to be fix ?

**Comment by ghost** [comment]
adrien75018, if you publish your html doc, I can try to find the reason, may be my patch is not complete.

**Comment by ghost** [comment]
Sorry, I've closed this issue by mistake. Reopen: https://github.com/amplafi/htmlcleaner/issues/#issue/4

**Comment by adrien75018** [comment]
all-x my html doc is very huge, i got the bug in makeTree function when i try to clean html from url : <br> http://www.pixmania.com/jeux-video-ps3-ca02-cable-peritel-av/frfr3553425_jvavis.html
