### ISSUE TITLE
Bug in HtmlCleaner.makeTree/closeSnippet

### ISSUE THREAD

**Issue by ghost** [amplafi/htmlcleaner#4]
Sorry, I've closed issue by mistake. Reopen https://github.com/amplafi/htmlcleaner/issues/closed/#issue/2

makeTree called recursively in closeSnippet.
childBreaks and openTags fields contains indexes in nodeList which is parameter of makeTree.
But childBreaks field value not stored like openTags. It causes wrong behaviour, NPEs in my case when nodeList.get(index) == null.

Don't know how to attach test html file here...

Simple patch:

<pre>
--- a/src/org/htmlcleaner/HtmlCleaner.java
+++ b/src/org/htmlcleaner/HtmlCleaner.java
@@ -875,10 +875,13 @@ public class HtmlCleaner {
                 if (itemsToMove != null) {
                        OpenTags prevOpenTags = _openTags;
                        _openTags = new OpenTags();
+                        ChildBreaks prevChildBreaks = _childBreaks;^M
+                        _childBreaks = new ChildBreaks();^M
                        makeTree(itemsToMove, itemsToMove.listIterator(0));
                     closeAll(itemsToMove);
                     startTagToken.setItemsToMove(null);
                     _openTags = prevOpenTags;
+                        _childBreaks = prevChildBreaks;^M
                 }

                 TagNode newTagNode = createTagNode(startTagToken);
</pre>

**Comment by patmoore** [comment]
o.k... will look at this

**Comment by patmoore** [comment]
Can you add a test case that demonstrates the error? Don't worry about it being perfect ( doesn't have to compile ) but something so I get what the issue is and what the correct behavior. You can send it to me via email if needed.

**Comment by patmoore** [comment]
nvm ! I see what you are saying....

**Comment by patmoore** [comment]
fixed -- please verify.

**Comment by ghost** [comment]
Thanks, my problem is solved.
